### ISSUE TITLE
Rename AppImages to "portable" instead of "setup" to reflect their functionality and avoid confusing the user

### ISSUE THREAD

**Issue by anh0516** [Foxxey/NullClient#9]
GNU/Linux AppImages are portable executables that self-extract their contents into RAM, not self-extracting installers like you would find on Windows to install a program to the system. They should be renamed as such to "NullClient-portable-linux-$arch.AppImage."

As a side note, why is the repository empty? Where is the source code? I want to build the software myself.

**Comment by Foxxey** [comment]
it is closed source.
